server:
  port: 8888
eureka:
  instance:
    hostname: eureka-server
  client:
    fetch-registry: false  #不从eureka上来获取服务的注册信息
    register-with-eureka: false #不把自己注册到eureka上
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # http://${eureka.instance.hostname}:${server.port}/eureka/